### ISSUE TITLE
Incomprehensible error message

### ISSUE THREAD

**Issue by jernst** [taligen/taligen#18]
% taligen all-release-ubos.tlt 
    Traceback (most recent call last):
      File "/usr/bin/taligen", line 315, in <module>
        main()
      File "/usr/bin/taligen", line 306, in main
        script = collect_pass(args)
      File "/usr/bin/taligen", line 252, in collect_pass
        script["steps"] = read_through_file(".", args.tl_file, script["parameters"], {}, deque())
      File "/usr/bin/taligen", line 209, in read_through_file
        call_file = call_file_match.group(1) + ".tl"
    AttributeError: 'NoneType' object has no attribute 'group'

**Comment by jernst** [comment]
This may have been caused by me not giving parentheses in a `call` statement.
